import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import { auth } from "../firebase/clientApp";
import { useAuthState } from "react-firebase-hooks/auth";

export default function Home() {

  // Firebase user status
  const [user, loading, error] = useAuthState(auth);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar user={user} />
      <main>
        <div className='container mx-auto'>
          <div className='pt-8'>
            <h1 className='text-3xl'>Big Guzzlers Club</h1>
            <p>Learn How to Invest</p>
            <p>See Environemtal Stocks</p>
            <p>Invest and Grow Your Garden</p>
            <p>Grow Your Garden and Save Trees</p>
            <p>Visually See Your Profit Grow</p>
          </div>
        </div>

      </main>

    </div>
  )
}
